### ISSUE TITLE
Attributes in annotations to specify Constraint, Index (etc.) name.

### ISSUE THREAD

**Issue by ancpru** [doctrine/orm#7666] opened 2019-04-03 08:50 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | no

#### Summary

Doctrine automatically generates the names of the constraints/indexes for @OneToMany, @ManyToMany, They are sometimes a bit cryptic when working on the DB. It would be
nice to have an attribute like "constraintName" in the definition.

In general I think that it would be nice to have more db-schema hints in order to make automatic schema generation easier and more straight forward. 

For example, cascading (update, delete) might not make sense for ORM, but it can be useful to let the DB take care of it.

**Comment by Ocramius** [comment] 2019-04-03 08:58
`ON UPDATE` cascade operations are something that will not be re-introduced in ORM. See also https://github.com/doctrine/orm/issues/7574#issuecomment-479335970 

Please use a migration tool with custom-written migrations for customising constraint names and cascade operations that are not supported by the ORM. Closing as duplicate of #3753

**Closed by Ocramius** 2019-04-03 08:58 UTC
