### ISSUE TITLE
DiscriminatorColumn fieldName is not set in AnnotationDriver

### ISSUE THREAD

**Issue by Zayon** [doctrine/orm#7106] opened 2018-03-02 10:36 UTC
In branch 2.6 
Given I have an Entity : 

```php
/**
 * @ORM\Entity()
 * @ORM\Table(name="table")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="db_column", type="string", fieldName="fieldName")
 * @ORM\DiscriminatorMap({"foo" = "Bar"})
 */
abstract class MyEntity
{
}
```

Then I have : 
```php
dump($this->em->getClassMetadata(MyEntity::class)->discriminatorColumn);
```

```
array:5 [
  "name" => "db_column"
  "type" => "string"
  "length" => 255
  "columnDefinition" => null
  "fieldName" => "db_column" // Should be "fieldName"
]
```

Fix is :
```
$metadata->setDiscriminatorColumn(
    [
        'name'             => $discrColumnAnnot->name,
        'type'             => $discrColumnAnnot->type ?: 'string',
        'length'           => $discrColumnAnnot->length ?: 255,
        'columnDefinition' => $discrColumnAnnot->columnDefinition,
        'fieldName'        => $discrColumnAnnot->fieldName ?: $discrColumnAnnot->name,
    ]
);
```
In https://github.com/doctrine/doctrine2/blob/2.6/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php#L253

PR incoming
Edit : `We only accept PRs to "master"` well PR not incoming then. :cry:

**Comment by Ocramius** [comment] 2018-03-02 12:47
Note that a discriminator has no real `fieldName` - should probably not
even exist...

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Zayon** [comment] 2018-03-05 12:43
Well what I want to accomplish is to have a single repository that can return any of inherited class.

like this:
```
$instance = $this->myEntityRepository->findOneBy([
    'discriminatorFieldName' => 'foo'
    'someField' => 'someValue',
]);

echo get_class($instance); // 'Bar'
```

Anyway `DiscriminatorColumn` should either have a `fieldName` property correctly set or no `fieldName` property at all.

**Comment by Ocramius** [comment] 2018-03-05 12:50
This won't work by design, because the discriminator is *NOT* a field. The fact that it has a field in the metadata is a different story, and IMO the `fieldName` should not exist at all there.

@guilhermeblanco maybe this is already fixed in `master`?

**Comment by guilhermeblanco** [comment] 2018-03-05 17:06
IIRC, I dropped the `fieldName` from DiscriminatorColumn already in master.

**Closed** 2020-12-07 21:26 UTC

**Comment by beberlei** [comment] 2020-12-07 21:31
This seems to be dead code that was never used in 2.x
