### ISSUE TITLE
Partial hydration of toMany associations without results does not initialize PersistentCollection

### ISSUE THREAD

**Issue by egonolieux** [doctrine/orm#6808] opened 2017-11-02 15:37 UTC
To avoid performance issues using fetch joins, I hydrate some of my toMany associations using partial hydration:

`SELECT someEntity, PARTIAL mainEntity.{id} FROM \Entity\MainEntity mainEntity ...`

If the query returns no results, the Doctrine PersistentCollection object remains uninitialized causing lazy loading to be triggered if the collection is accessed.

Is this intended behavior? To resolve this at the moment, I am forcing the PersistentCollection into an initialized state using `setInitialized`.

**Comment by SylvG** [comment] 2017-12-12 10:24
We confirm because we have the same problem here. Thanks for the temporary workaround.

**Comment by Ocramius** [comment] 2017-12-12 10:25
> Is this intended behavior? 

Most likely not - requires a test case and then we can look at where the offending code is located

**Comment by carherco** [comment] 2019-04-30 14:58
Exactly same issue to me. How can I help with a test case? Attaching a zip with Entities, Repositories and sql data is ok?

**Comment by Ocramius** [comment] 2019-05-01 20:52
See https://github.com/doctrine/doctrine2/tree/master/tests/Doctrine/Tests/ORM/Functional/Ticket for examples of previously written integration tests

**Comment by carherco** [comment] 2019-05-21 09:20
Hi, @Ocramius 

At the end, it was not a bug.

If I use LEFT JOIN it works like a charm. Could be closed in my opinion.

**Comment by Ocramius** [comment] 2019-05-21 09:58
Closing as per https://github.com/doctrine/orm/issues/6808#issuecomment-494311703

**Closed by Ocramius** 2019-05-21 09:58 UTC
Labels: Bug, Missing Tests

**Comment by egonolieux** [comment] 2020-09-16 15:18
@Ocramius I stumbled upon this issue again for another project and can confirm this issue is still present. I think @carherco simply meant that he found a working solution using fetch joins (LEFT JOIN) instead.

I looked at the integration tests you referenced, but I have limited knowledge about Doctrine internals. Can you provide me more guidance on how to write a test for this issue?

**Comment by carherco** [comment] 2020-09-16 19:02
I think (not sure 100%) that my original query was not retrieving any records from the database, so Doctrine receives nothing and can't hydrate nothing. 

With the LEFT JOIN, the database returns some records with empty associations and doctrine can do its job.

I will try to find my query to confirm that was my case.
