### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 3 passed to Doctrine\DBAL\Platforms\AbstractPlatform::modifyLimitQuery

### ISSUE THREAD

**Issue by firegore2** [doctrine/orm#7887] opened 2019-11-04 21:03 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.7.x-dev

#### Summary
PHP Version = 7.2.1 and 7.2.2
Breaks when I try to merge an entity or when use $em->getRepository(":MyEntity")->findOneBy method.

Fatal error: Uncaught TypeError: Argument 3 passed to Doctrine\DBAL\Platforms\AbstractPlatform::modifyLimitQuery() must be of the type integer, null given, called in /var/www/3dsouvenirs/onlinemarket/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php on line 1097 and defined in /var/www/3dsouvenirs/onlinemarket/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php on line 2949
--

![image](https://user-images.githubusercontent.com/23504988/68157477-00f37d00-ff4e-11e9-9b3d-89d688ceb7c2.png)

#### Previous behavior

Everything works correctly

#### Current behavior
The program crashes

#### How to reproduce
Use any of this methods:

 - $entity_manager->merge($myEntity)
 - $entity_manager->getRepository(":MyEntity")->find
 - $entity_manager->getRepository(":MyEntity")->findBy
 - $entity_manager->getRepository(":MyEntity")->findOneBy

**Comment by greg0ire** [comment] 2019-11-04 21:10
Looks like a solution could be to backport 5d6b5a706ff95ea884bbcad22b660efbc219f240 on 2.7 (or even lower?)

**Comment by firegore2** [comment] 2019-11-04 21:48
> Parece que una solución podría ser hacer backport [5d6b5a7](https://github.com/doctrine/orm/commit/5d6b5a706ff95ea884bbcad22b660efbc219f240) en 2.7 (¿o incluso más bajo?)
It has been failed since 3 days (11/04/2019)

**Comment by firegore2** [comment] 2019-11-04 21:48
> Looks like a solution could be to backport [5d6b5a7](https://github.com/doctrine/orm/commit/5d6b5a706ff95ea884bbcad22b660efbc219f240) on 2.7 (or even lower?)

it has been failed since 3 days (11/04/2019)

**Comment by Ocramius** [comment] 2019-11-04 21:50
Is this reproducible via test case, please?

**Comment by firegore2** [comment] 2019-11-04 22:48
now works fine with 2.7.x-dev

![image](https://user-images.githubusercontent.com/23504988/68164533-4ec3b180-ff5d-11e9-8029-5785e88b2ed0.png)

I don't know why but I deleted the vendor/doctrine folder and update with composer and now this function haven't the parameter type

**Comment by SenseException** [comment] 2019-11-10 22:01
Please introduce a test case that breaks because of the error mentioned above. It would help a lot.

**Comment by lcobucci** [comment] 2019-11-12 10:54
It seems this is not a problem. Closing here for now, please reopen if you find this again :+1:

**Closed by lcobucci** 2019-11-12 10:54 UTC
