### ISSUE TITLE
The class 'DateTime' was not found in the chain configured namespaces App\Entity since update to doctrine/orm 2.8

### ISSUE THREAD

**Issue by fabien007** [doctrine/orm#8369] opened 2020-12-04 18:44 UTC
Since I updated to doctrine/orm 2.8 i got this error
"The class 'DateTime' was not found in the chain configured namespaces App\Entity"
When i do a query->getResult();
doctrine/orm 2.7.4 working great

**Comment by beberlei** [comment] 2020-12-04 18:47
Duplicate of https://github.com/doctrine/orm/issues/8366

**Closed by beberlei** 2020-12-04 18:47 UTC
