### ISSUE TITLE
orm:validate-schema struggles with index over VARCHAR(255) UTF8MB4

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [doctrine/orm#7790] opened 2019-08-06 07:19 UTC
### Bug Report

The Doctrine ORM Schema-Tool wants to recreate my custom index each time.

The Problems seems to be that MariaDB creates the index over the first 191 chars of the UTF8-MB4 VARCHAR(255) column and Doctrine wants it to go over the full 255 characters.

Setting the max length to 100 on the column fixes the problem.

### How to reproduce

Use this entity:
```php
<?php

/**
 * @ORM\Table(name="my_table",indexes={@ORM\Index(name="idx_content_hash", columns={"content_hash"})})
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks
 */
class MyTable
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @var string
     * @ORM\Column(type="string", name="content_hash", nullable=true)
     */
    protected $contentHash;

...
}
```

I'm using MariaDB 10.1.40 (dockerized on Ubuntu bionic).

SQL for the table (exported from Sequel Pro):
```sql
CREATE TABLE `my_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
   `content_hash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_content_hash` (`content_hash`(191)),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

Calling `doctrine orm:validate-schema` on the CLI reports
```
Mapping
-------

 [OK] The mapping files are correct.                                            

Database
--------

 [ERROR] The database schema is not in sync with the current mapping file.
```

Calling `doctrine orm:schema-tool:update` on the CLI reports
```
 The following SQL statements will be executed:

     DROP INDEX idx_content_hash ON my_table;
     CREATE INDEX idx_content_hash ON my_table (content_hash);
```

Running these 2 SQLs wont fix the reported problem and loops back to the above statements.

#### Expected behavior

Either the database should be in sync already or the provided SQL statements should bring it into sync.

I'm guessing Maria will only take the first 191 Bytes into account for the index (its utf8_mb4, so 191 chars is the max for an index).
And thats whats aggravating doctrine? Reducing the length of `content_hash` to 100 chars fixes the problem (-> CLI commands show "database in sync").

### Doctrine Versions in use

```
doctrine/annotations                         v1.6.1            
doctrine/cache                               v1.8.0            
doctrine/collections                         v1.6.2            
doctrine/common                              v2.10.0           
doctrine/dbal                                v2.9.2            
doctrine/doctrine-module                     2.1.9             
doctrine/doctrine-orm-module                 2.1.5             
doctrine/event-manager                       v1.0.0            
doctrine/inflector                           v1.3.0            
doctrine/instantiator                        1.2.0             
doctrine/lexer                               1.1.0             
doctrine/migrations                          2.1.1             
doctrine/orm                                 v2.6.3            
doctrine/persistence                         1.1.1             
doctrine/reflection                          v1.0.0            
```

**Comment by SenseException** [comment] 2019-08-14 11:26
Thank you for opening this issue. Is the 191 in `content_hash(191)` also happening when ORM creates the table? This is an interesting issue because for the following example:

``` sql
-- Your example, but with an unique index
CREATE TABLE `my_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
   `content_hash` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_content_hash` (`content_hash`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO my_table (content_hash) VALUES ('123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345');
INSERT INTO my_table (content_hash) VALUES ('1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890');

-- WHERE has the value of the second INSERT
select content_hash from my_table WHERE content_hash = '1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890';
```

I get an empty result here, because the index handles the value as the same. It would be nice if you can show us how the create statement of ORM itself looks like.

MariaDB 10.1 is still supported but not the newest one and I would appreciate if you can test this on the other minor versions too for gathering informations for this issue.

**Comment by Ocramius** [comment] 2019-08-24 11:57
> and Doctrine wants it to go over the full 255 characters.

This is correct: I'd rather say that the DB should reject creating the index in first place, if no length is specified. The fact that MariaDB silently creates an index of reduced length is bothersome, and should most likely be reported upstream.

See https://florian.ec/blog/mysql-doctrine-utf8
See https://github.com/symfony/symfony-docs/issues/6398

Closing as duplicate of #5563 instead.

**Closed by Ocramius** 2019-08-24 11:57 UTC
