### ISSUE TITLE
Doctrine ORM tries to recreate partial indexes with the same definition every time.

### ISSUE THREAD

**Issue by skobkin** [doctrine/orm#6218] opened 2017-01-08 15:58 UTC
I've just encountered strange behavior when Doctrine ORM 2.5.5 tries to recreate some of indexes each time when I'm generating the migration or using `doctrine:schema:update` in my project.

I have following indexes definition:

```php
/**
 * @ORM\Table(name="telegram_accounts", schema="users", indexes={
 *      @ORM\Index(name="subscriber_notification_idx", columns={"subscriber_notification"}, options={"where": "subscriber_notification = TRUE"}),
 *      @ORM\Index(name="rename_notification_idx", columns={"rename_notification"}, options={"where": "rename_notification = TRUE"}),
 * })
 * @ORM\Entity(repositoryClass="Skobkin\Bundle\PointToolsBundle\Repository\Telegram\AccountRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Account
```

[Full entity code](https://bitbucket.org/skobkin/point-tools/src/cc29168d8307a2bf90b8b2af159fec29a5d8be0e/src/Skobkin/Bundle/PointToolsBundle/Entity/Telegram/Account.php?at=master&fileviewer=file-view-default#Account.php-8)

Every time I do that it generates following SQL:

```sql
-- You can also see that index names are generated without schema name which is other bug (I think it's known)
DROP INDEX rename_notification_idx;
DROP INDEX subscriber_notification_idx;
CREATE INDEX rename_notification_idx ON users.telegram_accounts (rename_notification) WHERE rename_notification = TRUE;
CREATE INDEX subscriber_notification_idx ON users.telegram_accounts (subscriber_notification) WHERE subscriber_notification = TRUE;
```

Even if I apply this migration or do `doctrine:schema:update --force` it will do that next time again.

My stack:

- PHP 7.0.14
- PostgreSQL 9.6.1
- symfony/symfony v2.7.21
- doctrine/annotations v1.3.0
- doctrine/cache v1.6.1
- doctrine/collections v1.3.0
- doctrine/common v2.6.2
- doctrine/data-fixtures v1.2.2
- doctrine/dbal v2.5.5
- doctrine/doctrine-bundle 1.6.4
- doctrine/doctrine-cache-bundle 1.3.0
- doctrine/doctrine-fixtures-bundle 2.3.0
- doctrine/doctrine-migrations-bundle v1.2.1
- doctrine/inflector v1.1.0
- doctrine/instantiator 1.0.5
- doctrine/lexer v1.0.1
- doctrine/migrations 1.4.1
- doctrine/orm v2.5.5

My project's [`config.yml`](https://bitbucket.org/skobkin/point-tools/src/cc29168d8307a2bf90b8b2af159fec29a5d8be0e/app/config/config.yml?at=master&fileviewer=file-view-default#config.yml-58)

**Comment by Ocramius** [comment] 2017-01-08 16:00
@skobkin does this come up also with 2.5.4?

**Comment by skobkin** [comment] 2017-01-08 16:09
@Ocramius Yes. I've just downgraded doctrine/orm to 2.5.4

```
  - Removing doctrine/orm (v2.5.5)
  - Installing doctrine/orm (v2.5.4)
```

Then generated new migration with following code:

```php
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('DROP INDEX users.rename_notification_idx');
        $this->addSql('DROP INDEX users.subscriber_notification_idx');
        $this->addSql('CREATE INDEX rename_notification_idx ON users.telegram_accounts (rename_notification) WHERE rename_notification = TRUE');
        $this->addSql('CREATE INDEX subscriber_notification_idx ON users.telegram_accounts (subscriber_notification) WHERE subscriber_notification = TRUE');
    }
```

Then I've done `doctrine:migration:migrate`, then `doctrine:schema:update --dump-sql` and here it is:

```
$ sf doc:sche:up --dump-sql
DROP INDEX subscriber_notification_idx;
DROP INDEX rename_notification_idx;
CREATE INDEX subscriber_notification_idx ON users.telegram_accounts (subscriber_notification) WHERE subscriber_notification = TRUE;
CREATE INDEX rename_notification_idx ON users.telegram_accounts (rename_notification) WHERE rename_notification = TRUE;
```

**Comment by Ocramius** [comment] 2017-01-08 16:13
@skobkin so ORM version is not causing this? Can you check with different DBAL and ORM versions to see if this is a regression?

**Comment by skobkin** [comment] 2017-01-08 16:16
@Ocramius Yes I can. Which versions you think will be more efficient to try?

**Comment by Ocramius** [comment] 2017-01-08 16:17
@skobkin I'd try 2.4.latest of both ORM and DBAL, then 2.5.0 of both. If the bug is reproducible in 2.4.0, then this is a new bug, not a regression.

**Comment by skobkin** [comment] 2017-01-08 17:01
`doctrine/orm` 2.4.8, `doctrine/dbal` 2.4.5 - can't reproduce due to lack of `options` support in `@Index` annotation:

```
$ sf doc:sche:up --dump-sql
...                                                                                                                                                          
  [Doctrine\Common\Annotations\AnnotationException]                                                                                                                                                   
  [Creation Error] The annotation @ORM\Index declared on class Skobkin\Bundle\PointToolsBundle\Entity\Telegram\Account does not have a property named "options". Available properties: name, columns
```

Changing `doctrine/orm` and `doctrine/dbal` both to 2.5.0 forced me to use `--with-dependencies`:

```
  - Removing doctrine/annotations (v1.3.0)
  - Installing doctrine/annotations (v1.3.1)
    Downloading: 100%         

  - Removing doctrine/common (v2.6.2)
  - Installing doctrine/common (v2.5.3)
    Loading from cache

  - Removing doctrine/dbal (v2.5.5)
  - Installing doctrine/dbal (v2.5.0)
    Downloading: 100%         

  - Removing doctrine/orm (v2.5.6)
  - Installing doctrine/orm (v2.5.0)
    Downloading: 100%
```

After that I generated new migration:

```php
// Seems like 2.5.0 in comparison with 2.5.5 have some problems with named indexes (I also generated migration which renamed IDX_SOME_HASH to human readable names after some of composer updates recently)
// https://bitbucket.org/skobkin/point-tools/src/fd3cd2d5171e043ab8011890d89eaf63bd6504d1/app/DoctrineMigrations/Version20170108152129.php?at=master&fileviewer=file-view-default
$this->addSql('ALTER INDEX subscriptions.author_idx RENAME TO IDX_22DA64DDF675F31B');
$this->addSql('ALTER INDEX subscriptions.subscriber_idx RENAME TO IDX_22DA64DD7808B1AD');

// The problem is still here:
$this->addSql('DROP INDEX subscriber_notification_idx');
$this->addSql('DROP INDEX rename_notification_idx');
$this->addSql('CREATE INDEX subscriber_notification_idx ON users.telegram_accounts (subscriber_notification) WHERE subscriber_notification = TRUE');
$this->addSql('CREATE INDEX rename_notification_idx ON users.telegram_accounts (rename_notification) WHERE rename_notification = TRUE');
```

After execution of this migration `doc:sche:up --dump-sql` returns this:

```sql
DROP INDEX subscriber_notification_idx;
DROP INDEX rename_notification_idx;
CREATE INDEX subscriber_notification_idx ON users.telegram_accounts (subscriber_notification) WHERE subscriber_notification = TRUE;
CREATE INDEX rename_notification_idx ON users.telegram_accounts (rename_notification) WHERE rename_notification = TRUE;
```

Seems like the problem was introduced with `@Index(options={})` support.

**Comment by Ocramius** [comment] 2017-01-08 17:02
Hmm, wondering if DBAL is able to extract column options from an existing DB in MySQL...

**Comment by andreasferber** [comment] 2017-03-29 12:52
Try putting parentheses around your partial index WHERE clause:

    @ORM\Index(name="subscriber_notification_idx", columns={"subscriber_notification"}, options={"where": "(subscriber_notification = TRUE)"}),

The way `getListTableIndexesSQL()` in `Doctrine\DBAL\Platform\PostgreSqlPlatform` queries the PostgreSQL system tables leads to those parentheses being added if they aren't already there, which makes the schema tool notice a difference.

**Comment by Siregacvek** [comment] 2018-04-13 13:38
Had the same issue.
Solution is to put paretheses around WHERE clause (as andreasferber suggested) + use lower-case "true". So the proper string will be:

@ORM\Index(name="subscriber_notification_idx", columns={"subscriber_notification"}, options={"where": "(subscriber_notification = true)"}),

**Comment by hacfi** [comment] 2019-01-19 01:49
I've come across the same issue:
Stack:
PHP 7.2.12
MySQL 5.7.21
doctrine/dbal v2.9.1
doctrine/orm  v2.6.3
symfony/symfony v4.2.1


```
...
 * @ORM\Table(
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="IDX_UNIQ_CUSTADDR_FKCUST_DEFBILLADDR", columns={"fk_customer"}, options={"where": "
 * (is_default_billing_address = true)"}),
 *         @ORM\UniqueConstraint(name="IDX_UNIQ_CUSTADDR_FKCUST_DEFSHIPADDR", columns={"fk_customer"}, options={"where": "
 * (is_default_shipping_address = true)"})
 *     }
 * )
...
```

**Comment by hacfi** [comment] 2019-01-19 02:17
False alarm in my case: I used this on a previous project with Postgresql and trying it with MySQL now which doesn't support partial indexes. The schema tool compares the index coming from the db that doesn't have a where clause with the index generated from the mapping which has a where clause.

**Comment by tasselchof** [comment] 2019-03-12 22:34
I have an issue with index:

rate_modifier_id = 3 AND state NOT IN ('new')

doctrine/dbal                v2.9.2
doctrine/orm                 v2.6.3

**Comment by trickeyone** [comment] 2019-04-23 23:38
I've been getting this issue for a while (since 2015), can't give a specific version, but whatever the version was in 2015.
It also occurs for foreign keys. It will add drops for FKs that haven't been changed.

**Comment by BunnyHolder** [comment] 2019-04-26 03:59
Having same problem.

```bash
doctrine/annotations                v1.6.1   
doctrine/cache                      v1.8.0   
doctrine/collections                v1.6.1   
doctrine/common                     v2.10.0  
doctrine/data-fixtures              v1.3.1   
doctrine/dbal                       v2.9.2   
doctrine/doctrine-bundle            1.10.2   
doctrine/doctrine-cache-bundle      1.3.5    
doctrine/doctrine-fixtures-bundle   3.1.0    
doctrine/doctrine-migrations-bundle v1.3.2   
doctrine/event-manager              v1.0.0   
doctrine/inflector                  v1.3.0   
doctrine/instantiator               1.2.0    
doctrine/lexer                      v1.0.1   
doctrine/migrations                 v1.8.1   
doctrine/orm                        v2.6.3   
doctrine/persistence                1.1.1    
doctrine/reflection                 v1.0.0
```

```php
$this->addSql('ALTER TABLE employee_schedule_breaks DROP FOREIGN KEY FK_4F7C782A8C03F15CAA9E377A');
$this->addSql('DROP INDEX IDX_4F7C782AAA9E377A8C03F15C ON employee_schedule_breaks');
$this->addSql('ALTER TABLE 
          employee_schedule_breaks 
        ADD 
          CONSTRAINT FK_4F7C782A8C03F15CAA9E377A FOREIGN KEY (employee_id, date) REFERENCES employee_schedule (employee_id, date) ON DELETE CASCADE');
```

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="employee_schedule_breaks")
 */
class EmployeeScheduleEntryBreak
{
    /**
     * @ORM\ManyToOne(targetEntity="EmployeeScheduleEntry", inversedBy="breaks")
     * @ORM\JoinColumns({
     *      @ORM\JoinColumn(name="employee_id", referencedColumnName="employee_id", onDelete="CASCADE"),
     *      @ORM\JoinColumn(name="date", referencedColumnName="date", onDelete="CASCADE"),
     * })
     * @var EmployeeScheduleEntry
     */
    private $entry;

    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="xxx\EmployeeBundle\Entity\Employee")
     * @ORM\JoinColumn(name="employee_id", nullable=false, onDelete="CASCADE")
     * @var Employee
     */
    private $employee;

    /**
     * @ORM\Column(name="date", type="date", nullable=false)
     * @var Date
     */
    private $date;
}
```

```php
/**
 * @ORM\Entity(repositoryClass="xxx\CalendarBundle\Entity\Repository\EmployeeScheduleEntryRepository")
 * @ORM\Table(name="employee_schedule")
 */
class EmployeeScheduleEntry
{
    /**
     * @ORM\Id
     * @ORM\ManyToOne(targetEntity="xxx\EmployeeBundle\Entity\Employee")
     * @ORM\JoinColumn(name="employee_id", nullable=false, onDelete="CASCADE")
     * @var Employee
     */
    private $employee;

    /**
     * @ORM\Column(name="date", type="date", nullable=false)
     * @ORM\Id
     * @var Date
     */
    private $date;
}
```

**Comment by lyrixx** [comment] 2019-06-11 14:01
Same issue here. With 
* doctrine/dbal 2.9.1 => OK
* doctrine/dbal 2.9.2 => KO

**Comment by kocur1508** [comment] 2019-06-18 06:00
Had a same issue with droping and creating index. Adding parentheses worked just fine for me.

` options={"where": "(current = true)"}`

**Comment by gnutix** [comment] 2019-07-09 08:29
Same as @ernestas-s :

```sql
ALTER TABLE urlstructure_refrub DROP FOREIGN KEY FK_5D39E57A23A1B569;
ALTER TABLE urlstructure_refrub DROP FOREIGN KEY FK_5D39E57A37C6C822;
ALTER TABLE urlstructure_refrub ADD CONSTRAINT FK_5D39E57A23A1B569 FOREIGN KEY (urlstructure_id) REFERENCES Url_Structure (id);
ALTER TABLE urlstructure_refrub ADD CONSTRAINT FK_5D39E57A37C6C822 FOREIGN KEY (refrub_id) REFERENCES Ref_Rub (id);
ALTER TABLE urlstructure_area DROP FOREIGN KEY FK_B1CD9FB223A1B569;
ALTER TABLE urlstructure_area DROP FOREIGN KEY FK_B1CD9FB2BD0F409C;
ALTER TABLE urlstructure_area ADD CONSTRAINT FK_B1CD9FB223A1B569 FOREIGN KEY (urlstructure_id) REFERENCES Url_Structure (id);
ALTER TABLE urlstructure_area ADD CONSTRAINT FK_B1CD9FB2BD0F409C FOREIGN KEY (area_id) REFERENCES Area (id);
```

```php
/**
 * @ORM\Table(
 *          name="Url_Structure",
 *          indexes={
 *             @ORM\Index(name="type_idx", columns={"type"})
 *         }
 * )
 * @ORM\Entity()
 */
class UrlStructure
{
    /**
     * @ORM\ManyToMany(targetEntity="Vendor\OurBundle\Entity\RefRub", cascade={"persist"}, indexBy="lang", inversedBy="structures")
     * @ORM\JoinTable(name="urlstructure_refrub",
     *      joinColumns={@ORM\JoinColumn(name="urlstructure_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="refrub_id", referencedColumnName="id")}
     * )
     */
    private $refRub;

    /**
     * @ORM\ManyToMany(targetEntity="Vendor\OurBundle\Entity\Area", cascade={"persist"})
     * @ORM\JoinTable(name="urlstructure_area",
     *      joinColumns={@ORM\JoinColumn(name="urlstructure_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="area_id", referencedColumnName="id")}
     * )
     */
    private $areas;
}

**Comment by bmxpapr** [comment] 2019-11-19 13:00
Same issue here with the following stack:
```
- PHP 7.2.19-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:16:55) ( NTS )
- mysqld  Ver 5.6.43 for Linux on x86_64 (MySQL Community Server (GPL))
- symfony/symfony                     v4.2.11
- doctrine/annotations                v1.8.0
- doctrine/cache                      v1.8.1
- doctrine/collections                v1.6.2
- doctrine/common                     v2.11.0
- doctrine/dbal                       v2.9.2
- doctrine/doctrine-bundle            1.9.1
- doctrine/doctrine-cache-bundle      1.3.3
- doctrine/doctrine-migrations-bundle v2.0.0
- doctrine/event-manager              v1.0.0
- doctrine/inflector                  v1.3.0
- doctrine/instantiator               1.2.0
- doctrine/lexer                      1.1.0
- doctrine/migrations                 2.1.1
- doctrine/orm                        v2.6.4
- doctrine/persistence                1.1.1
- doctrine/reflection                 v1.0.0

```
I also confirm that reverting `doctrine/dbal` to `2.9.1` solves the issue, so it points to a bug in `2.9.2`

**Comment by yvoyer** [comment] 2019-12-03 14:15
I made a PR to reproduce the issue in DBAL. https://github.com/doctrine/dbal/pull/3458
I'll check if it is still a WIP or not.

**Comment by ostrolucky** [comment] 2019-12-11 19:47
Closing here since it's DBAL and not ORM issue.

**Closed by ostrolucky** 2019-12-11 19:47 UTC
Labels: Bug, Missing Tests

**Comment by lyrixx** [comment] 2019-12-12 10:06
I guess we can all use https://github.com/doctrine/dbal/issues/2866 to track progression on this issue

**Comment by lyrixx** [comment] 2019-12-12 10:09
@ostrolucky Could you move this issue to the DBAL repo ? thanks
