### ISSUE TITLE
Incompatibility between `getArrayResult()` new type hint and use of `indexBy()`

### ISSUE THREAD

**Issue by benjamintoussaint** [doctrine/orm#8503] opened 2021-02-22 20:24 UTC
Cs fixes1 #8475 brought this change of `AbstractQuery` which I find incompatible with the use of `indexBy()`:
https://github.com/doctrine/orm/commit/f83322201771fc8db6b0a18b7d82fd51e893cc02#diff-65b30cb7319fd94159051fe212c87565a4ffd15a796fa0db4983c477076b88c8R798

~~@return array~~
@return array<int,mixed>

The new type hint is incompatible with a result indexed with a string property:

```php
$qb = $userRepository
    ->createQueryBuilder('u')
    ->indexBy('u', 'u.firstName')
    ->getQuery()
    ->getArrayResult()
;
```

I noticed the same issue with the same change for `getScalarResult()`.

I have thought of no alternative but to revert the change.

What do you think about this?

**Comment by stlrnz** [comment] 2021-03-02 13:43
I can confirm this issue.
In my case, i use `groupBy()` in combination with `getArrayResult()` and expect the array index to be string.

The updated return annotation released with 2.8.2 conflicts with my own annotation and causes Psalm to report some (false) issues.

**Comment by stof** [comment] 2021-03-16 09:50
@stlrnz `groupBy` won't put string keys in the array. It is about adding a `GROUP BY` in the generated SQL query, not about indexing the hydrated result.

The case reported by @benjamintoussaint about `indexBy` is valid though.

**Comment by stlrnz** [comment] 2021-03-16 09:52
Yeah, I already noticed this. Sorry for the confusion.

**Comment by greg0ire** [comment] 2021-03-16 17:19
> I have thought of no alternative but to revert the change.

@benjamintoussaint or we could simply do this: `mixed[]`

**Closed** 2021-03-21 21:11 UTC
Labels: BC Break, Bug

**Comment by ovidals** [comment] 2021-04-08 16:20
Is this a breaking change? so no semantic versioning?

**Comment by stof** [comment] 2021-04-08 16:30
@ovidals that was a mistake when making the phpdoc types more precise (combined with an API where the precise return type depends on the query being executed). that was not an intentional breaking change (and it has already been fixed)

**Comment by ovidals** [comment] 2021-04-08 16:49
@stof I see in the 2.8.4 there is another BC. I say that because we upgraded today from 2.8.1 to 2.8.4 and the app crashed due to an yml (it was? can't remember) error.

**Comment by stof** [comment] 2021-04-08 17:50
if you have another problem, please open a new issue to report it

**Comment by ThomasLandauer** [comment] 2021-10-30 14:18
@stlrnz Did you get `indexBy` to work in combination with `groupBy`? I came to the conclusion that this is not possible and just wanted to suggest this as a new feature. Example:
```php
$this->createQueryBuilder('a', 'a.month')
    ->select('SUM(a.amount)')
    ->groupBy('a.month')
    ->getQuery()
    ->getArrayResult()
;
```
Actual result:
```
array:4 [
  0 => array:1 []
  1 => array:1 []
  2 => array:1 []
  3 => array:1 []
]
```
Desired result:
```
array:4 [
  "Jan" => array:1 []
  "Feb" => array:1 []
  "March" => array:1 []
  "April" => array:1 []
]

```
**EDIT**: Just found out myself: It needs to be included in the select: `->select('a.month, SUM(a.amount)')`
