### ISSUE TITLE
Call to a member function resolveAssociationEntries() on boolean {"detail":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function resolveAssociationEntries() on boolean at /www/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultQueryCache.php:140)"}

### ISSUE THREAD

**Issue by mingmingxianseng** [doctrine/orm#7266] opened 2018-06-19 05:18 UTC
**The following mistakes occur occasionally，and I can't find the solution**

```
Call to a member function resolveAssociationEntries() on boolean {"detail":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function resolveAssociationEntries() on boolean at /www/vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultQueryCache.php:140)"}
```

>  version: doctrine/orm V2.6.0 
>  in  DefaultQueryCache.php at line 140 

```php
        $entries   = $region->getMultiple($cacheKeys);
        // @TODO - move to cache hydration component
        foreach ($cacheEntry->result as $index => $entry) {
            $entityEntry = is_array($entries) && array_key_exists($index, $entries) ? $entries[$index] : null;

            if ($entityEntry === null) {
                if ($this->cacheLogger !== null) {
                    $this->cacheLogger->entityCacheMiss($regionName, $cacheKeys->identifiers[$index]);
                }

                return null;
            }

```

I think the parameter $entityEntry sometimes will be  false , then occur the mistakes. 

change `if ($entityEntry === null) `  to `if ($entityEntry === null || $entityEntry === false ) ` . 
Is this a good solution ? 

I need your help. Thank you very much.

**Comment by javabudd** [comment] 2018-08-15 04:41
+1

This issue started happening to me when I switched my redis `maxmemory-policy` to `allkeys-lru`

**Comment by Ocramius** [comment] 2018-08-15 04:59
Also on newer releases?

**Comment by javabudd** [comment] 2018-08-15 05:41
I'm currently on 2.6.2

**Comment by Ocramius** [comment] 2018-08-15 05:44
Fixing the conditional is incorrect there: would need to change the fetch operation so that multiple misses don't become `false[]`

**Comment by Ocramius** [comment] 2018-08-15 05:45
Can this be reproduced with a failing test case?

**Comment by javabudd** [comment] 2018-08-15 05:54
I'll try and reproduce

**Comment by mingmingxianseng** [comment] 2018-08-16 03:35
```

   ## in  Doctrine\Common\Cache\RedisCache.php  +72

    protected function doFetchMultiple(array $keys)
    {
        $fetchedItems = array_combine($keys, $this->redis->mget($keys));

        // Redis mget returns false for keys that do not exist. So we need to filter those out unless it's the real data.
        $foundItems   = [];

        foreach ($fetchedItems as $key => $value) {
            # change this line to     if (false !== $value )
            if (false !== $value || $this->redis->exists($key)) {
                $foundItems[$key] = $value;
            }
        }

        return $foundItems;
    }
```

I create a new class extends RedisCache and  change `false !== $value || $this->redis->exists($key)`  to  `false !== $value`.

The problem was solved temporarily.

**Comment by Ocramius** [comment] 2018-08-16 05:04
Please don't suggest ugly workarounds when a solution here is possible:

 1. Send a test case
 2. Send a patch to the original code (including said test case)

**Comment by Ocramius** [comment] 2018-08-17 07:59
A cache miss can be emulated, and that's what should happen in the test
scenario

**Comment by mingmingxianseng** [comment] 2018-08-17 10:01
normal cache's value's type is object . but in this case , the cache's value  is  "false".
so it  throw exception `Call to a member function resolveAssociationEntries() on boolean` .

**Comment by Ocramius** [comment] 2018-08-17 10:02
Yes: let's put it in a test, reproduce the cache behavior there and figure out how to fix it afterwards (and only afterwards! Test comes first.) :-)

**Comment by javabudd** [comment] 2019-05-13 15:26
Upgrading the Redis engine from 4 -> 5 seems to have alleviated the issue for me.

**Comment by Ocramius** [comment] 2019-05-13 17:46
Closing here due to missing test scenario.

**Closed by Ocramius** 2019-05-13 17:46 UTC
Labels: Bug, Missing Tests

**Comment by umpirsky** [comment] 2019-07-23 10:31
Same issue exists in `v2.6.3`.
