### ISSUE TITLE
Optimistic Lock with Timestamps check

### ISSUE THREAD

**Issue by niltong09** [doctrine/orm#6413] opened 2017-04-26 15:13 UTC
Hello,

I'm using doctrine with symfony, and using the optimistic lock feature in a timestamp field. I've incurred in a problem where the timestamps are equal but doctrine says it is not, to resolve my problem, I've modified the lock method of UnitOfWork, to when the object to check are both instances of DateTime Class, the check is made through the getTimestamp() function of both objects, it worked for me, I would like to contribute this modification, but I don't know if it's in the interest of the community here, and I would like to know.

Just for consideration, I'm using doctrine with a Microsoft SQL Server 2008 R2, the field time in the schema is Timestamp, and the mapping in doctrine is datetime.

I'm putting the modified UnitOfWork.php with the topic for anyone that want to see.
[UnitOfWork.php.zip](https://github.com/doctrine/doctrine2/files/958879/UnitOfWork.php.zip)

**Comment by Jean85** [comment] 2017-04-28 13:14
To ease of reading, I will paste here your modification:

if ($entityVersion instanceof \DateTime && $lockVersion instanceof \DateTime) {
	    if ($entityVersion->getTimestamp() != $lockVersion->getTimestamp()) {
		throw OptimisticLockException::lockFailedVersionMismatch($entity, $lockVersion, $entityVersion);
	    }
	} else {
	    if ($entityVersion != $lockVersion) {
		throw OptimisticLockException::lockFailedVersionMismatch($entity, $lockVersion, $entityVersion);
	    }
	}

How would this change anything? DateTime objects are comparable with the `!=` operator, so what are you trying to accomplish? The only case where this could have any sense is if the original datetime where created with microseconds value, but since they are values hydrated from a DB, I highly that that is the case!

**Comment by lcobucci** [comment] 2017-04-29 10:45
@niltong09 I agree with @Jean85 here, there's no need to do such check since the [comparison just works since PHP 5.2.2](https://3v4l.org/EOaJa).

Can you give us more information on the reason and possibly a test case that reproduces it (you can use https://github.com/doctrine/doctrine2/blob/03972c9c3a6d16b1c6c6e43d5cc2561f105df8fa/tests/Doctrine/Tests/ORM/Functional/Ticket/GH5762Test.php as example).

**Comment by beberlei** [comment] 2020-12-08 01:23
No progress on reproduce case, closing as per luis description of that it should work.

As for timestamps are the same, do your timestamps maybe include microseconds? I.e. getTimestamp is not `->format('U.u')`

**Closed by beberlei** 2020-12-08 01:23 UTC
Labels: Bug, Missing Tests
