### ISSUE TITLE
2.6.4. breaks queries using objects as parameters

### ISSUE THREAD

**Issue by kdambekalns** [doctrine/orm#7827] opened 2019-09-23 10:25 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.6.4

#### Summary

Upgrading from 2.6.3 to 2.6.4 triggers an error related to obejct parameters in queries.

#### Previous behavior

It worked ;)

#### Current behavior

```
Catchable Fatal Error: Object of class Neos\ContentRepository\Domain\Model\Workspace could not be converted to string in /application/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php line 77 - See also: 20190923101155fe8fe7.txt
19-09-23 10:12:56 1506       CRITICAL                       Exception in line 145 of /application/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php: An exception occurred while executing 'SELECT n0_.persistence_object_identifier AS persistence_object_identifier_0, n0_.version AS version_1, n0_.pathhash AS pathhash_2, n0_.path AS path_3, n0_.parentpathhash AS parentpathhash_4, n0_.parentpath AS parentpath_5, n0_.identifier AS identifier_6, n0_.sortingindex AS sortingindex_7, n0_.removed AS removed_8, n0_.dimensionshash AS dimensionshash_9, n0_.lastmodificationdatetime AS lastmodificationdatetime_10, n0_.lastpublicationdatetime AS lastpublicationdatetime_11, n0_.hiddenbeforedatetime AS hiddenbeforedatetime_12, n0_.hiddenafterdatetime AS hiddenafterdatetime_13, n0_.dimensionvalues AS dimensionvalues_14, n0_.properties AS properties_15, n0_.nodetype AS nodetype_16, n0_.creationdatetime AS creationdatetime_17, n0_.hidden AS hidden_18, n0_.hiddeninindex AS hiddeninindex_19, n0_.accessroles AS accessroles_20, n0_.workspace AS workspace_21, n0_.contentobjectproxy AS contentobjectproxy_22, n0_.movedto AS movedto_23 FROM neos_contentrepository_domain_model_nodedata n0_ WHERE n0_.workspace IN (?) AND (EXISTS (SELECT n1_.persistence_object_identifier FROM neos_contentrepository_domain_model_nodedimension n1_ WHERE n1_.nodedata = n0_.persistence_object_identifier AND n1_.name = 'language' AND n1_.value IN (?)) OR NOT EXISTS (SELECT n2_.persistence_object_identifier FROM neos_contentrepository_domain_model_nodedimension n2_ WHERE n2_.nodedata = n0_.persistence_object_identifier AND n2_.name = 'language')) AND n0_.pathhash = ?' with params [{"Flow_Injected_Properties":["nodeDataRepository","publishingService","nodeService","now","reflectionService","persistenceManager"]}, "en", "476f5936360c6893a04fe012e80711fb"]:
```

#### How to reproduce

Update `doctrine/orm` from 2.6.3 to 2.6.4 and see it fail. The code is complex, but the main part involved should be:

```
        $queryBuilder->select('n')
            ->from(NodeData::class, 'n')
            ->where('n.workspace IN (:workspaces)')
            ->setParameter('workspaces', $workspaces, Connection::PARAM_STR_ARRAY);
```

My _wild guess_ would that the fix #7527 in PR #7528 might cause it.

**Comment by Ocramius** [comment] 2019-09-23 10:29
> `->setParameter('workspaces', $workspaces, Connection::PARAM_STR_ARRAY);`

This should indeed not be converted to identifiers, since you're binding a string array, yet declared `$workspaces`, which I assume is a `Workspace[]`?

**Comment by kdambekalns** [comment] 2019-09-23 10:46
Might be true… I am quite sure we did that parameter hint on purpose, and it worked before. So… I'll try to fix that.

**Comment by Ocramius** [comment] 2019-09-23 11:22
Can you maybe come up with a test case verifying your use-case (that is green on `2.6.3`, and red on `2.6.4`)?

**Comment by kdambekalns** [comment] 2019-09-23 12:31
I'll try the test-case, but removing the wrong parameter type hint or actually passing an array of strings solves the issue for our code. So I guess it's really a "side-effect we used so far" that has been removed. Too bad I cannot remeber what we actually fixed back then by adding it…

**Comment by lcobucci** [comment] 2019-09-23 14:43
@kdambekalns should we close this issue, then?

**Comment by kdambekalns** [comment] 2019-09-23 14:46
Fell free, if I come around to creating a valid test case, I'll let you know. Thanks!

**Closed** 2019-09-23 14:55 UTC
Labels: Bug, Missing Tests

**Comment by snebes** [comment] 2019-09-25 16:32
I've outlined this issue in more detail in #7832.  In v2.6.3, the $type was verified before being used, where in v2.6.4, the $type is blindly accepted without type-checking.

**Comment by Ocramius** [comment] 2019-09-25 23:04
> $type is blindly accepted without type-checking

This is the correct/expected behavior

**Comment by szambonurek** [comment] 2019-10-17 06:22
2.6.4 introduced bc breaking change. This code worked in 2.6.3 and befire. Now it fails 
```
$ids = $qb->getQuery()->getArrayResult()
// ['id' => 1, 'id' => 2]
$qb2->setParameter('ids', $ids, Connection::PARAM_INT_ARRAY);
```
This change is causig this:
**\Doctrine\ORM\Query::resolveParameterValue::435**
```
if ($parameter->typeWasSpecified()) {
     return [$parameter->getValue(), $parameter->getType()];
}
```

**Comment by Ocramius** [comment] 2019-10-17 07:15
@szambonurek can you write a test case? I cannot see parameter binding in your example (specifically, query and parameter format)

`$ids` is supposed to be an `int[]` there: what do you have instead?
