### ISSUE TITLE
MySQL 5.7 datetime precision support

### ISSUE THREAD

**Issue by foaly-nr1** [doctrine/orm#6305] opened 2017-02-25 13:55 UTC
```php
/**
 * @ORM\Column(type="datetime", precision=6)
 */
private $updatedAt;
```

Source: https://dev.mysql.com/doc/refman/5.7/en/fractional-seconds.html

> MySQL 5.7 has fractional seconds support for TIME, DATETIME, and TIMESTAMP values, with up to microseconds (6 digits) precision:
> 
> To define a column that includes a fractional seconds part, use the syntax type_name(fsp), where type_name is TIME, DATETIME, or TIMESTAMP, and fsp is the fractional seconds precision. For example:
> 
> ```mysql
> CREATE TABLE t1 (t TIME(3), dt DATETIME(6));
> ```
> 
> The fsp value, if given, must be in the range 0 to 6. A value of 0 signifies that there is no fractional part. If omitted, the default precision is 0. (This differs from the standard SQL default of 6, for compatibility with previous MySQL versions.)

This has already been done for Mongo DB, see https://github.com/doctrine/mongodb-odm/issues/1061 and https://github.com/doctrine/mongodb-odm/issues/1063.

**Comment by coudenysj** [comment] 2017-08-21 14:46
See https://github.com/doctrine/dbal/issues/1020

**Comment by holtkamp** [comment] 2018-03-30 16:15
Also see https://github.com/doctrine/dbal/issues/2873

**Comment by TomHAnderson** [comment] 2018-09-07 18:01
Here's a work around: https://blog.tomhanderson.com/2018/09/datetime-with-microseconds-for-mysql-in.html

**Comment by flaushi** [comment] 2019-04-01 19:43
@TomHAnderson Thanks for that!
In order for your code to also be compatible with postgres, I added 
```
if($platform instanceof MySqlPlatform)
            return 'TIMESTAMP(6) WITHOUT TIME ZONE';
        else
            return 'DATETIME(6)';
```

**Comment by TomHAnderson** [comment] 2019-04-01 20:04
@flaushi Using the Timestamp data type in MySQL can be odd.  I recommend you use `DATETIME(6)` for your MySQL instead of timestamp:  https://stackoverflow.com/questions/409286/should-i-use-the-datetime-or-timestamp-data-type-in-mysql

**Comment by flaushi** [comment] 2019-04-01 20:50
You are right, I had a typo.
```
if($platform instanceof PostgreSqlPlatform)
            return 'TIMESTAMP(6) WITHOUT TIME ZONE';
        else
            return 'DATETIME(6)';
```

**Comment by flaushi** [comment] 2019-04-01 20:53
Actually I don't even understand, why doctrine cuts off the microsecond part. 
Until I ran into trouble with this, I was naturally assuming microseconds would be stored.
AFAIK, a timestamp has 8 bytes on mysql in any case, so it also has nothing to do with saving storage.

**Comment by Majkl578** [comment] 2019-04-02 01:15
Duplicate of #2873

**Comment by Majkl578** [comment] 2019-04-02 01:16
> Actually I don't even understand, why doctrine cuts off the microsecond part.

Wery likely due to portability and compatibility, but as seen in #2873 this is something that can be improved in DBAL 3.0.

I'm going to close this issue in favor of #2873, please continue discussion there.

**Closed by Majkl578** 2019-04-02 01:16 UTC
Labels: Improvement

**Comment by Majkl578** [comment] 2019-04-02 01:18
Duplicate of doctrine/dbal#2873
