### ISSUE TITLE
@GeneratedValue(strategy="NONE") not working on @Id

### ISSUE THREAD

**Issue by masseelch** [doctrine/orm#7007] opened 2018-01-24 17:38 UTC
I am trying to have my primary column NOT getting assigned the `auto_increment` option by doctrine.

Following the docs i used the following approach:

```
 /**
     * @var integer
     *
     * @ORM\Column(name="Auftragsnummer", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $id;
``` 

Doctrine does ignore this and will always attempt to change the Column:
![image](https://user-images.githubusercontent.com/12862103/35347471-838a6224-0135-11e8-8414-459ce9547458.png)

When trying to insert a new record, i cannot set the ID and always get 
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
``` 
since doctrine does not take my code-generated Id but tries to use the database value (which does not provide one, since `auto_increment` is not set).

**Comment by Ocramius** [comment] 2018-01-26 10:09
This needs a test case to be reproduced.

**Comment by zeleniy** [comment] 2019-09-03 12:36
Any success??

**Comment by Ocramius** [comment] 2019-09-03 13:09
Closing here: please open a new issue once a test case reproducing the issue is available.

**Closed by Ocramius** 2019-09-03 13:09 UTC
Labels: Bug, Missing Tests

**Comment by Tagirijus** [comment] 2021-06-20 09:20
I have a similar issue, when trying to use `NONE` as the ID strategy. The thing on my end was: I had a loop with which I import multiple entries. And inside the loop I only did a `persist()` for the entity. When I change this to `persist()` **and** `flush()` (inside the loop) it works here.

I think that it might be that otherwise _only persisted_ entites with manually set IDs could become a problem, when another entity during the import (without flushing in the meantime) gets persisted as well ...

Info: I am totally new to doctrine ... so maybe I do not understand something else here in general, but again: it works for me when just flushing one entity directly on my import method.

Maybe this might help somebody in the future. (-;
