### ISSUE TITLE
PersistentCollection::isDirty for owner side entity always returned false after clear

### ISSUE THREAD

**Issue by diversantvlz** [doctrine/orm#7567] opened 2019-01-11 19:09 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.6.3

#### Summary

Group relationship to User many to many unidirectional. Group is owner side.
```php
/**
 * @ORM\Entity()
 */
class UserGroup
{
    /**
     * @var int|null
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var Collection
     * @ORM\ManyToMany(targetEntity="User", cascade={"all"})
     * @ORM\JoinTable(name="users_groups",
     *      joinColumns={@ORM\JoinColumn(name="group_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")}
     *      )
     */
    protected $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return Collection
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    /**
     * @param Collection $users
     * @return UserGroup
     */
    public function setUsers(Collection $users): UserGroup
    {
        $this->users = $users;
        return $this;
    }
}
```
```php
/**
 * @ORM\Entity()
 */
class User
{
    /**
     * @var int|null
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
}
```
Example
```php
        $group = new UserGroup();
        $user = new User();
        $group->getUsers()->add($user);
        $em->persist($group);
        $em->flush();
        $groupId = $group->getId();
        $em->clear();
        
        $group = $em->getRepository(UserGroup::class)->find($groupId);
        $count = $group->getUsers()->count() // 1
        $isDirty = $group->getUsers()->isDirty(); // false
        $group->getUsers()->clear();
        $count = $group->getUsers()->count() // 0
        $isDirty = $group->getUsers()->isDirty(); // false
```
PersistentCollection::isDirty for owner side entity always returned false after clear. This happens because in the method clear called method takeSnapshot. Maybe not call takeSnapshot in clear method? What do you think about this?
#### Current behavior

PersistentCollection::isDirty always returned false after clear

#### How to reproduce

Find any owning side entity with not empty ManyToMany relation and clear collection with called PersistentCollection::clear. Call PersistentCollection::isDirty, result to be false.

#### Expected behavior

PersistentCollection::isDirty always must be true after clear

**Comment by skylord123** [comment] 2020-12-05 19:06
This is a duplicate of #4173

If you clear a ManyToMany relation it will take a snapshot after clearing (and when it takes a snapshot it sets `isDirty` to false)

**Comment by zkimi** [comment] 2022-02-24 11:37
Hello,
Is there a way to correct this issue?

**Comment by greg0ire** [comment] 2022-02-27 17:22
Duplicate of #4173

**Closed by greg0ire** 2022-02-27 17:22 UTC
