### ISSUE TITLE
IDENTITY() function hydrate data as string even if entity is configured as int

### ISSUE THREAD

**Issue by jdeniau** [doctrine/orm#8281] opened 2020-09-22 14:08 UTC
Given the following request 

```php
$qb = $this->createQueryBuilder('cartitem')
    ->select('IDENTITY(cartitem.cart) as cartId')
    ->getQuery()
    ->getArrayResult()
;
```

The return will be : 
```
[
  1 => array:1 [
    "cartId" => "8982"
  ]
]
```

The cart id is hydrated as a string, but should be an integer.

If I changed the request to this:
```php
$qb = $this->createQueryBuilder('cartitem')
    ->select('cart.id as cartId')
    ->join('cartitem.cart', 'cart')
    ->getQuery()
    ->getArrayResult()
```
The result is a int (which is normal)

**Comment by SenseException** [comment] 2020-09-22 17:19
There's a PR that handles this issue: #8025

**Comment by jdeniau** [comment] 2020-09-22 19:02
@SenseException Great ! I looked in the issues but not in the PR.

I keep it open the time this PR is merged to avoid anyone to open the same issue 😉

**Comment by SenseException** [comment] 2020-09-22 19:47
If you don't mind I'll close this issue because it's a duplicate of #4641.

Still: Thank you for taking your time to report this.

**Closed by SenseException** 2020-09-22 19:47 UTC
