### ISSUE TITLE
Error launching psysh after installing doctrine/orm

### ISSUE THREAD

**Issue by marcosdipaolo** [doctrine/orm#7636] opened 2019-03-05 18:20 UTC
### Bug Report

Once i install doctrine/orm it's not possible to launch psysh. 
It's relevant to mention that psysh is installed globally,  configured to load vendor/autoload if there's any, and that everything goes ok until doctrine/orm is installed.
The error is: 
```
In Application.php line 895:

  Call to undefined method Symfony\Component\Console\Helper\QuestionHelper::getInputStream()

``` 

#### Expected behavior

Being able to install doctrine/orm and open psysh inside a project

**Comment by SenseException** [comment] 2019-03-05 23:19
How exactly is Doctrine involved in this? Have you tried to debug the reason for your error other than having the information that it broke after ORM was installed?

There's not much we can do with interoperability between different projects/libs as it is not a bug in a standalone ORM itself and I'm sure this issue will be closed as "can't fix".

**Comment by Ocramius** [comment] 2019-03-06 01:05
```
Call to undefined method Symfony\Component\Console\Helper\QuestionHelper::getInputStream()
```

This most likely indicates that the version of symfony/console shipped with psysh isn't compatible with the one requested by the ORM.

This is not something we can fix, but rather is to be handled by the psysh installation approach.

**Closed by Ocramius** 2019-03-06 01:05 UTC
Labels: Question
