### ISSUE TITLE
Select With

### ISSUE THREAD

**Issue by elvispdosreis** [doctrine/orm#7604] opened 2019-02-11 12:24 UTC
|    Q        |   A
|------------ | -----
| Version     | 2.6.0

### Support Question

I need to do a paging with my products, where I have a ratio of 1 to N with prices due to the problem [#7594](https://github.com/doctrine/orm/issues/7594) I can not bring doing a join, how can I make a select where I bring the products and then I get the prices and mix with the product table to produce the same rejustado of a join in the relationship, something similar to "with eloquent"

**Comment by Ocramius** [comment] 2019-02-11 12:47
Closing as duplicate of #7594

Please refer to https://www.doctrine-project.org/community/ for channels where to ask for support/questions.

**Closed by Ocramius** 2019-02-11 12:47 UTC
