### ISSUE TITLE
Doctrine 2.6 : Inheritance (instance of) does not work

### ISSUE THREAD

**Issue by christophe-mailfert** [doctrine/orm#6979] opened 2018-01-11 16:01 UTC
Hi guys,

Doctrine ORM version : 2.6.0

I'm currently migrating my project from symfony3 to symfony4 flex and my unit tests are failing. The reason:

Instance of does not generate correct sql request

Generated sql
```
WHERE (p0_.type IN ('stop', 'interest') AND p0_.client_id = 1)
```

Instead of
```
WHERE (p0_.type IN ('interest') AND p0_.client_id = 1)
```

Code in repository:
```
switch ($filters['type']) {
                case 'interest':
                    $query->from(Point::class, 'p')
                        ->andWhere($builder->expr()->isInstanceOf('p', Point::class));
                    break;
                case 'bus_stop':
                    $query->from(Point::class, 'p')
                        ->andWhere($builder->expr()->isInstanceOf('p', Point\BusStop::class));
                    break;
                default:
                    throw new InvalidArgumentException(sprintf('filters "type" %s is not a valid value.', $filters['type']));
            }
```

See you :)

**Comment by Majkl578** [comment] 2018-01-11 16:04
Can you please also share your entities/mapping to illustrate the inheritance tree? ideally as a test case that reproduces the bug? It'd be really helpful in order to identify the issue.
You can find test examples on https://github.com/doctrine/doctrine2/tree/v2.6.0/tests/Doctrine/Tests/ORM/Functional/Ticket.

Thanks.

**Comment by christophe-mailfert** [comment] 2018-01-11 16:08
Sure here is my entities:

```
/**
 * @ORM\Entity(repositoryClass="App\Repository\PointRepository")
 * @ORM\Table(name="point", options={"collate"="utf8_general_ci", "charset"="utf8", "engine"="InnoDB"})
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"interest" = "Point", "stop" = "App\Entity\Point\BusStop"})
 */
class Point
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", name="id")
     */
    protected $id;

...
}
```

```
/**
 * @ORM\Entity()
 * @ORM\Table(name="stop_point", options={"collate"="utf8_general_ci", "charset"="utf8", "engine"="InnoDB"})
 */
class BusStop extends Point
{
...
}
```

I will add a test as soon as possible :).

**Comment by lcobucci** [comment] 2018-01-15 11:06
@christophe-mailfert the SQL is being generated correctly, what's happening is that you're not using inheritance correctly.

Objects with type `BusStop` are also an instance of `Point`, e.g.:

```php
$elem = new BusStop();

var_dump($elem instanceof BusStop());
var_dump($elem instanceof Point());
```

Therefore if you're using `$builder->expr()->isInstanceOf('p', Point::class)`, the generated will use `interest` AND `stop` as filter.

This was a bug in v2.5.x, which was fixed in v2.6 (#6392).

**Comment by christophe-mailfert** [comment] 2018-01-15 11:14
Hey Icobucci,

Thx for your response. 

So with my current schema, it's not possible to handle inheritance ?

Should i transform Point to an Abstract class and create a child InterestPoint who extends AbstractPoint ? or there is another solution with current schema ?

Thx for advance.

**Comment by lcobucci** [comment] 2018-01-15 14:41
> So with my current schema, it's not possible to handle inheritance ?
> 
> Should i transform Point to an Abstract class and create a child InterestPoint who extends AbstractPoint ? or there is another solution with current schema ?

That's indeed a viable solution, and it won't require a redesign of your models.

**Comment by koseduhemak** [comment] 2018-01-18 13:39
The following does also not work in `2.6.0`:

```
/**
 * Class Project
 *
 * @ORM\Entity(repositoryClass="ProjectRepository")
 * @ORM\Table(options={"collate"="utf8mb4_unicode_ci", "charset"="utf8mb4"})
 */
class Project
{
    ...
}
```

```
/**
 * Class SubProject
 *
 * @ORM\Entity(repositoryClass="ProjectRepository")
 * @ORM\Table(options={"collate"="utf8mb4_unicode_ci", "charset"="utf8mb4"})
 */
class SubProject extends Project
{
    ...
}
```

Problem is that `$array = $this->entityManager->getRepository(Project::class)->findAll();` does not return any entities of type `SubProject`, only of type `Project`. However, there are many `null` values (I think every `SubProject` gets hydrated as `null` value) in the resulting `$array`.

The same code works with `2.5.14`.

**Comment by lcobucci** [comment] 2018-01-18 14:46
@koseduhemak your mapping seems invalid to me, since it doesn't follow any of the guidelines explained in http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html.

That might be the cause of not getting the correct data, however it's kind of scary that it used to work on `v2.5.14`.

**Comment by koseduhemak** [comment] 2018-01-18 15:00
@lcobucci Sorry, did some mistakes by copying and simplifying my example.
Corrected it in my previous answer (it was way more complex, but I tried to reduce complexity and make a shorter, easier to understand example).
I followed the guidelines here: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#single-table-inheritance

**Comment by lcobucci** [comment] 2018-01-18 15:34
@koseduhemak so you really don't have a `@DiscriminatorMap`? Could you try to send a PR with a failing functional test with this scenario (targeting `2.6`)?

**Comment by koseduhemak** [comment] 2018-01-18 16:51
@lcobucci nope, I do not explicitly specify a `@DiscriminatorMap`. I thought (and according to the docs), we do not necessarily specify one: "If no discriminator map is provided, then the map is generated automatically. The automatically generated discriminator map contains the lowercase short name of each class as key." (Source: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#single-table-inheritance, last bullet).

However, I tried to create a functional test reproducing my issue without luck. I tried `2.6` but also `2.5` and in both cases I get an exception `Doctrine\ORM\Mapping\MappingException: Entity 'Doctrine\Tests\Models\Project\SubProject' has to be part of the discriminator map of 'Doctrine\Tests\Models\Project\Project' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Doctrine\Tests\Models\Project\SubProject' an abstract class to avoid this exception from occurring.`.

This leads to the question, why, in my own project, I am able to specify `SINGLE_TABLE` inheritances without `@DiscrimintatorMap`.

**Comment by lcobucci** [comment] 2019-01-05 09:48
@insekticid the ORM should behave the same way as the language, there's no point in adding a flag to modify that behaviour.

In your case, I'd dare to say that you probably have a design issue when you say that a Page is an Article (that's the relation type you have when using inheritance in object oriented programming).

I'll close this as invalid since we don't have any failing test that proves the bug.

**Closed by lcobucci** 2019-01-05 09:48 UTC
Labels: Bug, Missing Tests

**Comment by insekticid** [comment] 2019-01-17 10:08
@lcobucci Today I modified Article to `abstract class AbstractArticle {}` and I have got same behavior with instanceOf. It propagates all Entities, that extends AbstractArticle - so there is no solution other than duplicating the same code to all of entities to avoid this
