### ISSUE TITLE
Deferred Explicit change tracking policy + removal + persist of objects leads to not-persisted changes

### ISSUE THREAD

**Issue by skurfuerst** [doctrine/orm#8230] opened 2020-08-07 08:44 UTC
... That's hard to describe, I'll try nevertheless :-)

## Background

- We use Deferred Explicit as change tracking policy; and we have a single entity which is enough to reproduce the issue.
- The entity is persisted in the database already, and we have loaded it as `$entity`.

## How to reproduce

- call `$entityManager->remove($entity);`
- modify the entity `$entity->setFoo('bar');`
- call `$entityManager->persist($entity);`
- call `$entityManager->flush();`
- EXPECTED: The entity should be updated in the database.
- ACTUAL: the entity is not updated.

## Root Cause Analysis:

- call `$entityManager->remove($entity);`
- modify the entity `$entity->setFoo('bar');`
- call `$entityManager->persist($entity);`
- call `$entityManager->flush();`
- EXPECTED: The entity should be updated in the database.
- ACTUAL: the entity is not updated.

**Comment by beberlei** [comment] 2020-09-13 13:02
Duplicate of #8231

**Closed by beberlei** 2020-09-13 13:02 UTC
