### ISSUE TITLE
isNull criteria doesn't work

### ISSUE THREAD

**Issue by BenWaNH** [doctrine/orm#7717] opened 2019-05-22 11:04 UTC
Hi,

i've an issue with isNull method from Expression class

this is an example i use in my entity :
```
public function getValidDiscountOffers(): Collection
{

        $expr = Criteria::expr();
        $criteria = Criteria::create()
            ->where($expr->eq('active', true))
            ->andWhere($expr->isNull('validityStart'))
        ;
        return $this->discountOffers->matching($criteria);
}
```

And this is the result SQL from log :

> WHERE t.user_id = ? AND te.active = ? [145,false] []

No trace about IS NULL
And If i try to replace my validityStart variable by another whose doesn't exist, no error returned
But if i replace isNull method by eq method an error is trigger ... It seems to skip my expression when isNull...

Thanks for reading
BenWa

**Comment by BenWaNH** [comment] 2019-05-22 11:15
Yes, I will write it next week. I have to stay my time for this week and I will use the filter in the meantime.
Thanks

**Comment by thicolares** [comment] 2019-10-20 19:23
Hey @BenWaNH , I've created a test case for that, but I was not able to reproduce the error (version 2.7). Looks good to me. I took the opportunity to create a functional test that demonstrates that. See #7874.

If so, maybe we could close this issue.

**Comment by hason** [comment] 2020-03-18 11:25
@thicolares This issue is valid for ManyToManyPersister and SqlValueVisitor https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/Persisters/SqlValueVisitor.php#L32-L36

**Comment by ndench** [comment] 2020-08-28 04:18
I can confirm that this issue exists for ManyToMany relationships but not for ManyToOne relationships.
Our entity model looks like this:

```
Organisation:
    - OneToMany TemplateTypes
Template:
    - ManyToMany TemplateTypes
TemplateType:
    - ManyToOne Organisation
    - ManyToMany Template
    - ?DateTime archivedAt
```

Doing a `Criteria::expr()->isNull('archivedAt')` on `Organisation::templateTypes` correctly filters out archived TemplateTypes.

Doing a `Criteria::expr()->isNull('archivedAt')` on `Template::templateTypes` when `templateTypes` is uninitialized does not filter correctly because `archived_at IS NULL` is left off the SQL query.

However, if `templateTypes` is initialized, then Criteria uses `array_filter` and it works as expected.

So the issue is only present when calling `PersistentCollection::matching` with an uninitialized collection with an many to many association.

**Comment by ndench** [comment] 2021-12-22 04:17
For anyone else who stumbles across this, I've been manually filtering these as a workaround:

```diff
- $this->templateTypes->matching(Criteria::create()->andWhere(Criteria::expr()->isNull('archivedAt')));
+ $this->templateTypes->filter(fn (TemplatType $type) => null === $type->getArchivedAt());
```

**Comment by MatTheCat** [comment] 2023-03-21 14:39
Just got hit by this one while calling `matching` on a lazy (happens with both `LAZY` or `EXTRA_LAZY`) collection.

BTW this issue seems to duplicate https://github.com/doctrine/orm/issues/5587 and https://github.com/doctrine/orm/issues/5827

**Closed** 2023-04-12 17:32 UTC
Labels: Missing Tests, Bug
